### ISSUE TITLE
[:blank:] is too wide

### ISSUE THREAD

**Issue by eush77** [micromatch/expand-brackets#1]
Both `[:space:]` and `[:blank:]` as defined in this module contain `\s`, which is not an escape sequence for any character, but rather a RegExp special character that represents the strict superset of both `[:space:]` and `[:blank:]`.

``` js
> expandBrackets.makeRe('[:blank:]').test('\v')
true // should be false
```

I think it is better to remove `\s` from both definitions.

**Comment by jonschlinkert** [comment]
great point. will mark this as a bug. 

want to do a pr?

**Comment by tunnckoCore** [comment]
@jonschlinkert i can PR, but it breaks cases in first test. i cleared them, but if it is okey and expected i cant push

**Comment by jonschlinkert** [comment]
maybe wait and see if @eush77  would like to do the pr first. then please, by all means a pr would be great. thanks!
